version: '3'

networks:
  app:
    driver: bridge

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
  kafka-data:
    driver: local
  zookeeper-data:
    driver: local
  debezium-data:
    driver: local

services:
  generator:
    image: 'baldezxniy/data-generator-service:latest'
    networks:
      - app
    depends_on:
      - postgres
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS={KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_SUBSCRIBED_TOPICS=${KAFKA_SUBSCRIBED_TOPICS}
    ports:
      - '8081:8080'

  analyser:
    image: 'baldezxniy/data-analyser-service'
    networks:
      - app
    depends_on:
      - postgres
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - KAFKA_SUBSCRIBED_TOPICS=${KAFKA_SUBSCRIBED_TOPICS}
      - HOST=${HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '8082:8082'

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    networks:
      - app
    env_file:
      - .env
#    environment:
#      - ZOOKEEPER_CLIENT_PORT=${ZOOKEEPER_CLIENT_PORT}
#      - ZOOKEEPER_TICK_TIME=${ZOOKEEPER_TICK_TIME}
    ports:
      - '2181:2181'
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    networks:
      - app
    env_file:
      - .env
#    environment:
#      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
#      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
#      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
#      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
#      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    ports:
      - '9092:9092'
    volumes:
      - kafka-data:/var/lib/kafka/data

  postgres:
    image: 'postgres:15.1-alpine'
    networks:
      - app
    env_file:
      - .env
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - '5437:5432'
    volumes:
      - kafka-data:/var/lib/kafka/data

  redis:
    image: redis:7.2-rc-alpine
    networks:
      - app
    env_file:
      - .env
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  debezium:
    image: 'debezium/connect:2.4.0.Final'
    networks:
      - app
    depends_on:
      - kafka
    env_file:
      - .env
    environment:
      - BOOSTRAP_SERVERS=${KAFKA_BOOSTRAP_SERVERS}
      - GROUP_ID=${DEBEZIUM_KAFKA_BROKER_ID}
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    user: root
    volumes:
      - debezium-data:/debezium/data
      - ./conf/:/on-startup/