spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${LOCAL_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

server.port: 8082

topics: ${KAFKA_SUBSCRIBE_TOPICS}

---
spring.config.activate.on-profile: docker